version: '3.1'
services:
  rabbitmq:
    container_name: 'rabbit-mq'
    image: rabbitmq:3.11.3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./rabbitmq-config/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq-config/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro

  orderdb:
    container_name: 'postgres-db-order'
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=orderdb
      - POSTGRES_USER=snr1012
      - POSTGRES_PASSWORD=viking

  paymentdb:
    container_name: 'postgres-db-payment'
    image: postgres:alpine
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=paymentdb
      - POSTGRES_USER=snr1012
      - POSTGRES_PASSWORD=viking

  shippingdb:
    container_name: 'postgres-db-shipping'
    image: postgres:alpine
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_DB=shippingdb
      - POSTGRES_USER=snr1012
      - POSTGRES_PASSWORD=viking

  orderservice:
    container_name: 'order-service'
    build:
      context: order-service
      dockerfile: Dockerfile
    image: orderservice:latest
    ports:
      - "8081:8081"
    depends_on:
      - discoveryservice
      - orderdb
    environment:
      POSTGRES_JDBC_USER: snr1012
      POSTGRES_JDBC_PASSWORD: viking
      SPRING_DATASOURCE_URL: "jdbc:postgresql://orderdb:5432/orderdb"

  paymentservice:
    container_name: 'payment-service'
    build:
      context: payment-service
      dockerfile: Dockerfile
    image: paymentservice:latest
    ports:
      - "8082:8082"
    depends_on:
      - discoveryservice
      - paymentdb
    environment:
      POSTGRES_JDBC_USER: snr1012
      POSTGRES_JDBC_PASSWORD: viking
      SPRING_DATASOURCE_URL: "jdbc:postgresql://paymentdb:5433/paymentdb"

  shippingservice:
    container_name: 'shipping-service'
    build:
      context: shipping-service
      dockerfile: Dockerfile
    image: shippingservice:latest
    depends_on:
      - discoveryservice
      - shippingdb
    ports:
      - "8083:8083"
    environment:
      POSTGRES_JDBC_USER: snr1012
      POSTGRES_JDBC_PASSWORD: viking
      SPRING_DATASOURCE_URL: "jdbc:postgresql://shippingdb:5434/shippingdb"

  gatewayservice:
    container_name: 'gateway-service'
    build:
      context: gateway-service
      dockerfile: Dockerfile
    image: gatewayservice:latest
    depends_on:
      - discoveryservice

    ports:
      - "8080:8080"

  discoveryservice:
    container_name: 'discovery-service'
    build:
      context: discovery-service
      dockerfile: Dockerfile
    image: discoveryservice:latest
    ports:
      - "8761:8761"
