version: '3.1'
services:
  rabbitmq:
    container_name: 'rabbit-mq'
    image: rabbitmq:3.11.3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./rabbitmq-config/definitions.json:/etc/rabbitmq/definitions.json:ro
      - ./rabbitmq-config/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro

  order-db:
    container_name: 'postgres-db-order'
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=orderdb
      - POSTGRES_USER=snr1012
      - POSTGRES_PASSWORD=viking
      - POSTGRES_PORT=5432

  payment-db:
    container_name: 'postgres-db-payment'
    image: postgres:alpine
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=paymentdb
      - POSTGRES_USER=snr1012
      - POSTGRES_PASSWORD=viking
      - POSTGRES_PORT=5433

  shipping-db:
    container_name: 'postgres-db-shipping'
    image: postgres:alpine
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_DB=shippingdb
      - POSTGRES_USER=snr1012
      - POSTGRES_PASSWORD=viking
      - POSTGRES_PORT=5434

  discovery-service:
    container_name: 'discovery-service'
    build:
      context: discovery-service
      dockerfile: Dockerfile
    image: discovery-service:latest
    environment:
      eureka.instance.hostname: discovery-service
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka/
    ports:
      - "8761:8761"


  gateway-service:
    container_name: 'gateway-service'
    build:
      context: gateway-service
      dockerfile: Dockerfile
    image: gateway-service:latest
    environment:
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
    ports:
      - "8080:8080"

  order-service:
    container_name: 'order-service'
    build:
      context: order-service
      dockerfile: Dockerfile
    image: order-service:latest
    ports:
      - "8081:8081"
    depends_on:
      - discovery-service
      - order-db
    environment:
      POSTGRES_JDBC_USER: snr1012
      POSTGRES_JDBC_PASSWORD: viking
      SPRING_DATASOURCE_URL: "jdbc:postgresql://order-db:5432/orderdb"
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka/

  payment-service:
    container_name: 'payment-service'
    build:
      context: payment-service
      dockerfile: Dockerfile
    image: payment-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - discovery-service
      - payment-db
    environment:
      POSTGRES_JDBC_USER: snr1012
      POSTGRES_JDBC_PASSWORD: viking
      SPRING_DATASOURCE_URL: "jdbc:postgresql://payment-db:5432/paymentdb"
      EUREKA_SERVER_URL: "http://discovery-service:8761/eureka"
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka/

  shipping-service:
    container_name: 'shipping-service'
    build:
      context: shipping-service
      dockerfile: Dockerfile
    image: shipping-service:latest
    depends_on:
      - discovery-service
      - shipping-db
    ports:
      - "8083:8083"
    environment:
      POSTGRES_JDBC_USER: snr1012
      POSTGRES_JDBC_PASSWORD: viking
      SPRING_DATASOURCE_URL: "jdbc:postgresql://shipping-db:5432/shippingdb"
      eureka.client.serviceUrl.defaultZone: http://discovery-service:8761/eureka/


