server:
  port: 8083
spring:
  rabbitmq:
    host: localhost
  application:
    name: shipping-service
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/shippingdb
    username: snr1012
    password: viking
