server:
  port: 8081
spring:
  rabbitmq:
    host: localhost
  application:
    name: order-service
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: 'jdbc:postgresql://localhost:5432/orderdb'
    username: snr1012
    password: viking
